spring.application.name=Prototipo_UEIV
spring.datasource.url=jdbc:postgresql://dpg-d740so3uibrs73ar3ko0-a.ohio-postgres.render.com:5432/fitbridge_db
spring.datasource.username=fitbridge_db_user
spring.datasource.password=fb6z9FcLylowO1oSxlGTarDyUP4ph6If
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect